# SPDX-FileCopyrightText: 2024 Ali Sajid Imami
#
# SPDX-License-Identifier: CC0-1.0

---
repos:
- repo: https://github.com/commitizen-tools/commitizen
  rev: v3.29.1
  hooks:
  - id: commitizen
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: check-illegal-windows-names
  - id: check-json
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-toml
  - id: check-xml
  - id: check-yaml
  - id: debug-statements
  - id: destroyed-symlinks
  - id: double-quote-string-fixer
  - id: end-of-file-fixer
  - id: name-tests-test
  - id: trailing-whitespace
    args:
    - --markdown-linebreak-ext=md
- repo: https://github.com/compilerla/conventional-pre-commit
  rev: v3.4.0
  hooks:
  - id: conventional-pre-commit
    args:
    - build
    - bump
    - chore
    - ci
    - docs
    - feat
    - fix
    - perf
    - refactor
    - revert
    - style
    - test
    stages:
    - commit-msg
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.5.5
  hooks:
  - id: forbid-crlf
  - id: remove-crlf
  - id: forbid-tabs
  - id: remove-tabs
- repo: https://github.com/adrienverge/yamllint
  rev: v1.35.1
  hooks:
  - id: yamllint
    args:
    - --config-file
    - .yamllint.yaml
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.42.0
  hooks:
  - id: markdownlint
- repo: https://github.com/sirosen/texthooks
  rev: 0.6.7
  hooks:
  - id: fix-smartquotes
  - id: fix-ligatures
  - id: forbid-bidi-controls
- repo: https://github.com/zricethezav/gitleaks
  rev: v8.21.0
  hooks:
  - id: gitleaks
- repo: https://github.com/fsfe/reuse-tool
  rev: v4.0.3
  hooks:
  - id: reuse
- repo: https://github.com/renovatebot/pre-commit-hooks
  rev: 38.124.0
  hooks:
  - id: renovate-config-validator
    language_version: 20.17.0
