---
# SPDX-FileCopyrightText: 2022 - 2024 Ali Sajid Imami
#
# SPDX-License-Identifier: CC0-1.0
extends: default
rules:
    line-length:
        max: 150
        level: warning
    truthy:
        check-keys: false
    indentation:
        spaces: 4
        indent-sequences: false
    comments:
        min-spaces-from-content: 1
