---
name: "CLA Assistant Workflow"
on:
    issue_comment:
        types: [created]
    pull_request_target:
        types: [opened, closed, synchronize]
permissions:
    actions: write
    contents: read
    pull-requests: write
    statuses: write
jobs:
    CLAAssistant:
        runs-on: ubuntu-latest
        steps:
        - name: "CLA Assistant"
          if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name
            == 'pull_request_target'
          uses: contributor-assistant/github-action@v2.6.1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            USE_DCO: ${{vars.USE_DCO}}
            PERSONAL_ACCESS_TOKEN: ${{ secrets.DCO_CLA_REPO_TOKEN }}
            CLA_URL: ""
            PROJECT_NAME: ${{github.event.repository.name}}
          with:
            path-to-signatures: '${{env.PROJECT_NAME}}/signatures/signatures.json'
            path-to-document: ${{ env.USE_DCO && "https://developercertificate.org/" || env.CLA_URL }} # e.g. a CLA or a DCO document
            branch: 'main'
            allowlist: step-security-bot,renovate[bot]
            remote-organization-name: Imamiland
            remote-repository-name: CLA-DCO-Record
            create-file-commit-message: 'Signature file not found. Creating file for storing ${{env.USE_DCO && "DCO" || "CLA"}} Signatures'
            custom-notsigned-prcomment: 'Thank you for contributing to $project. Please take a moment to sign the ${{ env.USE_DCO && "Developer Certificate
                of Origin (DCO)" || "Contributor Licensing Agreement (CLA)" }}. at $pathToCLADocument'
            use-dco-flag: ${{ env.USE_DCO || false }}
