---
name: "Add Label to Issue"
description: "Adds a specified label to an issue"
inputs:
  label:
    description: "Label to add to the issue"
    required: true
runs:
  using: "composite"
  steps:
    - name: Add Label
      uses: actions/github-script@v6
      with:
        script: |
          github.issues.addLabels({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            labels: [ "${{ inputs.label }}" ]
          })
